export enum MESSAGE_CODE {
  // common
  DEFAULT_SUCCESS = 'DEFAULT_SUCCESS',
  DEFAULT_ERROR = 'DEFAULT_ERROR',
  NOT_FOUND_DATA = 'NOT_FOUND_DATA',
  SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG',
  ERROR_MISSING_REQUIRED_CONDITION = 'ERROR_MISSING_REQUIRED_CONDITION',
}
